Your refinement is substantially correct. The decisive improvement is replacing the **external-filter model**

[
C_\infty \xrightarrow{L_i} C_i
]

with an **internal self-determination model**:

[
C_\infty
\xrightarrow{\delta_i}
\langle
\mathbb S_i,W_i,\Gamma_i
\rangle.
]

The remaining work is to distinguish what the texts explicitly state, what scholarship reconstructs, and what our framework adds. The final version below does that.

# Final Pratyabhijñā–Science Framework

## A source-controlled reconstruction of manifestation, contraction, finite agency and recognition

## Status key

Every proposition belongs to one of four levels:

[
\mathbf T=\text{explicitly textual}
]

[
\mathbf R=\text{strong scholarly reconstruction}
]

[
\mathbf C=\text{cross-disciplinary structural correspondence}
]

[
\mathbf H=\text{live philosophical hypothesis}
]

No correspondence with science should be presented as a translation or historical anticipation.

---

# 1. The primary ontological commitment

## Textual position

Pratyabhijñā does not begin with neutral phenomenality that is subsequently converted into consciousness.

Its ultimate reality is consciousness understood as the inseparability of:

[
C_\infty
========

\langle
P,V,F
\rangle
]

where:

[
P=\textit{prakāśa}
]

manifest actuality or luminosity;

[
V=\textit{vimarśa}
]

intrinsic self-apprehension, determination and articulation;

[
F=\textit{svātantrya}
]

freedom or autonomous power of self-determination.

These are analytical aspects of one reality, not three components assembled together. Utpaladeva’s philosophical project aims to show that individual consciousness is none other than the absolute freedom of the all-encompassing Lord, and that this can be uncovered through ordinary cognition, agency and experience. ([OUP Academic][1])

### Status

[
\mathbf T+\mathbf R
]

---

# 2. Why (C_\infty) must not be reduced to (M_\infty)

The earlier symbol:

[
M_\infty
========

\text{universal manifest capacity}
]

is too weak.

Utpaladeva’s ultimate is not merely a universal phenomenal field. It is supposed to possess four inseparable features:

[
C_\infty
========

\langle
\text{manifestation},
\text{unity},
\text{determination},
\text{agency}
\rangle.
]

It can:

* manifest changing contents;
* remain one through those changes;
* determine contents as specific objects;
* connect temporally separated cognitions;
* act without requiring an external agent;
* appear under limited forms without becoming divided into substances.

The school’s target is therefore:

[
\boxed{
\text{universal self-manifest agency}
}
]

not merely:

[
\text{universal phenomenality}.
]

### Status

[
\mathbf R
]

---

# 3. The self-determination operator

Define:

[
\delta_i
========

\text{one mode of consciousness determining itself finitely}.
]

This is our formal notation, not Abhinavagupta’s terminology.

It replaces the misleading picture:

[
C_\infty
+
\text{external filter}
\rightarrow
\text{finite consciousness}.
]

The more faithful model is:

[
\boxed{
C_\infty
\xrightarrow{\delta_i}
\langle
\mathbb S_i,W_i,\Gamma_i
\rangle
}
]

where:

[
\mathbb S_i
===========

\text{a nested embodied ecology functioning as one finite knower};
]

[
W_i
===

\text{its determinate objective world};
]

[
\Gamma_i
========

\text{the structured relation constituting knower and world together}.
]

The subject, body, limitations, objects and relations are not independently produced entities later connected together. They are mutually determining aspects of one finite manifestation.

### Status

[
\mathbf R+\mathbf H
]

---

# 4. The finite subject is modal, not fractional

A finite consciousness is not a spatial piece cut from universal consciousness:

[
C_i\not\subset C_\infty
]

in the ordinary part–whole sense.

Nor is it a second substance generated by universal consciousness:

[
C_\infty\not\rightarrow C_i
]

as a temporal causal event.

The intended relation is modal:

[
\boxed{
C_i
\equiv_i
C_\infty
}
]

meaning:

> The same reality operates under standpoint (i), with restricted knowledge, action, value, time and causal access.

A finite subject is therefore:

[
\boxed{
C_\infty
\text{ apprehending and enacting itself under a limited mode}.
}
]

Ratié’s reconstruction supports the claim that empirical subjects are limited aspects of one universal consciousness, while also stressing that consciousness is active and capable of assuming differentiated forms without losing its underlying unity. ([OUP Academic][1])

### Status

[
\mathbf R
]

---

# 5. The finite subject–world relation

The earlier sequential model:

[
C_i+B_i+G_i+SM_i\rightarrow W_i
]

is too close to a contemporary perception pipeline.

The Pratyabhijñā model is relational:

[
\boxed{
S_i\leftrightarrow W_i.
}
]

A finite subject is determinate only through:

* what it can know;
* what it cannot know;
* what it can affect;
* what can affect it;
* what it treats as external;
* what it identifies as itself.

An object is likewise determinate as an object manifest under a specific mode of cognition and exclusion.

Therefore:

[
\boxed{
\delta_i(C_\infty)
==================

\langle
\mathbb S_i,W_i,\Gamma_i
\rangle.
}
]

Subject and world arise together as poles within one contracted relation.

### Status

[
\mathbf R+\mathbf H
]

---

# 6. The structure of (\Gamma_i)

Define:

[
\Gamma_i
========

\langle
K_i,A_i,V_i,T_i,C_i,X_i
\rangle.
]

Here:

[
K_i=\text{restricted knowledge and access};
]

[
A_i=\text{restricted action and efficacy};
]

[
V_i=\text{finite valuation, need and attraction};
]

[
T_i=\text{sequential temporal access};
]

[
C_i=\text{particular causal and spatial situation};
]

[
X_i=\text{exclusive determination of self and other}.
]

The first five approximate the functional roles of the kañcukas.

The sixth—exclusion—is required to explain why limitation becomes an apparently independent subject confronting external objects.

---

# 7. The kañcukas as finite-agency coordinates

## Kalā

At *Tantrāloka* 9.183, *kalā* is distinguished from an ordinary instrument and is treated as an activating agency in relation to the finite doer. At 9.203, the remaining four limitations are called effects of *kalā* and remain filled with the condition of the experiencer. ([Wisdom Library][2])

Functional reconstruction:

[
\boxed{
\textit{kalā}
\rightsquigarrow
A_i
===

\text{restricted capacity to act}.
}
]

## Vidyā

[
\boxed{
\textit{vidyā}
\rightsquigarrow
K_i
===

\text{restricted discrimination and knowing}.
}
]

## Rāga

[
\boxed{
\textit{rāga}
\rightsquigarrow
V_i
===

\text{incompleteness, attraction and asymmetric valuation}.
}
]

## Kāla

[
\boxed{
\textit{kāla}
\rightsquigarrow
T_i
===

\text{division of action and experience into sequence}.
}
]

## Niyati

[
\boxed{
\textit{niyati}
\rightsquigarrow
C_i
===

\text{determinate allocation of causes, conditions and effects}.
}
]

At *Tantrāloka* 9.204, Māyā and these five are explicitly grouped as six coverings or limiting sheaths of consciousness, under which consciousness stands as a bound subject. ([Wisdom Library][3])

### Status

Textual functions:

[
\mathbf T
]

Finite-agent coordinates:

[
\mathbf C
]

---

# 8. The finite-agency constraint proposition

The defensible modern proposition is:

[
\boxed{
\text{A biologically or computationally finite agent requires bounded}
}
]

[
\boxed{
\text{information, action, valuation, temporal processing and causal reach.}
}
]

A finite agent cannot possess:

[
K_i=K_\infty,
\qquad
A_i=A_\infty,
\qquad
T_i=T_\infty
]

while remaining finite in the ordinary systems sense.

Likewise, without differences between present and preferred states:

[
V(s_1)=V(s_2)=\cdots
]

there is no basis for directed correction or policy selection.

This is not a deductive proof that every conceivable perspective must instantiate exactly five ontological coverings. It is a functional proposition about finite agency.

### Status

[
\mathbf C+\mathbf H
]

---

# 9. Limitation is not bondage

This distinction is essential.

Define the finite architecture:

[
L_i
===

\langle
K_i,A_i,V_i,T_i,C_i
\rangle.
]

It makes a particular embodied perspective possible.

But bondage requires more:

[
\boxed{
B_i
===

L_i
+
X_i
+
I_i
}
]

where:

[
X_i
===

\text{exclusive subject–object determination};
]

[
I_i
===

\text{identification of the finite standpoint as exhaustive}.
]

More explicitly:

[
\boxed{
B_i
===

L_i
+
\operatorname{AbsoluteIdentification}(\mathbb S_i)
+
\operatorname{Externalization}(W_i).
}
]

Finite senses, memory, embodiment and causal location do not by themselves constitute bondage.

Bondage is the apprehension:

[
\boxed{
\text{“This local organization is the complete and independent source of what I am.”}
}
]

### Status

[
\mathbf R+\mathbf H
]

---

# 10. Exclusion is not merely informational scarcity

A finite subject does not merely lack information.

It determines:

[
\text{I am this and not that}.
]

Its objects are likewise determined through exclusion:

[
x
=

\neg y\land\neg z\land\cdots
]

Pratyabhijñā appropriates Buddhist *apoha* theory but makes exclusion a mode of consciousness’s own fragmentation of an underlying unity. Abhinavagupta describes ordinary determination as consciousness fragmenting what is intrinsically complete so that practical ascertainment—such as “only the pot”—becomes possible. ([MDPI][4])

Therefore:

[
\boxed{
\text{restricted access}
\neq
\text{exclusive determination}.
}
]

A system may retain limited access after liberation:

[
L_i\neq0
]

while the exclusivity of its identity is transformed:

[
X_i\rightarrow X_i'.
]

### Status

[
\mathbf T+\mathbf R
]

---

# 11. Māyā

A source-controlled definition is:

[
\boxed{
\textit{Māyā}
=============

\text{the differentiating power through which consciousness appears}
}
]

[
\boxed{
\text{under separative and mutually exclusive determination}.
}
]

Our comparative reconstruction is:

[
\boxed{
\textit{Māyā}
\rightsquigarrow
\text{the conversion of integrated difference into standpoint-relative externality}.
}
]

Māyā is therefore not identical to:

* hallucination;
* false sensory information;
* predictive processing;
* an imaginary second universe;
* a perceptual model.

Predictive processing may describe how a finite system stabilizes its organism-relative world **after** restricted subject–world organization is in place.

Thus:

[
\textit{Māyā}
\rightarrow
\text{separative standpoint structure}
]

[
L_i
\rightarrow
\text{finite agent coordinates}
]

[
\text{predictive processing}
\rightarrow
\text{finite world stabilization}.
]

### Status

Textual core:

[
\mathbf T
]

Comparative formulation:

[
\mathbf C
]

---

# 12. The local subject is internally multiple

The finite organism should not be represented as one elementary agent:

[
S_i.
]

Use:

[
\boxed{
\mathbb S_i
===========

{s_i^1,s_i^2,\ldots,s_i^n}
}
]

where the (s_i^k) are partially autonomous processes coordinated into an organism-level organization.

They may include:

* cellular regulatory agencies;
* metabolic systems;
* immune processes;
* endocrine control;
* sensorimotor loops;
* neural hierarchies;
* reflective and social self-models.

Biernacki’s reading emphasizes both foundational subjectivity within materiality and a multiplicity of agencies within embodied life, rather than a sovereign Cartesian controller. Her work is philosophically generative, but reviewers have also noted that some of her extensions—especially regarding the operative sentience of matter—go beyond what direct textual evidence securely establishes. ([OUP Academic][5])

Therefore:

[
\boxed{
\text{finite embodiment}
========================

\text{a nested ecology of powers functioning provisionally as one life}.
}
]

### Status

Biernacki interpretation:

[
\mathbf R
]

Levin-compatible formulation:

[
\mathbf C
]

---

# 13. Matter

The strongest source-compatible formulation is not:

[
\text{matter is secretly a human-like mind}.
]

It is:

[
\boxed{
\text{matter is not ontologically external to conscious power}.
}
]

Materiality is one highly stabilized form of differentiation characterized by:

* persistence;
* resistance;
* opacity;
* causal regularity;
* spatial differentiation;
* delayed effects;
* relative independence between embodied standpoints.

Biernacki characterizes Abhinavagupta’s panentheism as locating foundational subjectivity at the core of materiality and using this to reject a strict opposition between consciousness and dead matter. ([OUP Academic][6])

Our reconstruction is:

[
\boxed{
\text{materiality}
==================

\text{self-articulating power stabilized as resistance and public regularity}.
}
]

This is a metaphysical interpretation, not a physical mechanism.

### Status

[
\mathbf R+\mathbf H
]

---

# 14. Cognition

A cognition must not be treated as a discrete object containing information.

The Pratyabhijñā analysis attributes to cognition at least:

[
\boxed{
\text{manifestation}
+
\text{determination}
+
\text{continuity}
+
\text{agency}.
}
]

## Minimal manifestation

The cognition does not require a second cognition merely to make it conscious.

## Determination

It manifests:

[
\text{this as this}
]

through exclusion of alternatives.

## Transformation

Consciousness assumes distinct cognitive forms without being exhausted by any one form.

## Continuity

Past and present acts can be apprehended within one recognitive sequence.

## Agency

Cognition is not merely an inert reception of forms.

Torella’s critical edition and translation are indispensable because Utpaladeva’s own *Vṛtti* clarifies these arguments and their sustained engagement with Buddhist epistemology. ([Iris][7])

### Status

[
\mathbf T+\mathbf R
]

---

# 15. The memory argument must be stated cautiously

The strong Pratyabhijñā intuition is:

[
\text{memory}
\neq
\text{mere persistence of information}.
]

Episodic memory presents:

[
\boxed{
\text{“I experienced this.”}
}
]

A causal trace can explain why information from an earlier event affects a later system.

It does not automatically explain the first-person attribution:

[
\text{this was my experience}.
]

However, memory does not provide a simple knock-down proof of a numerically identical enduring subject. Recent analysis using Utpaladeva’s own objection argues that it is difficult to establish that episodic memory recalls the subjective “for-me-ness” of a past experience rather than merely its represented contents. The failure of the Buddhist memory argument would not itself refute intrinsic awareness, but it weakens memory as a decisive proof of it. ([Cambridge University Press][8])

Therefore the correct result is:

[
\boxed{
\text{memory distinguishes information persistence from experienced ownership,}
}
]

but:

[
\boxed{
\text{it does not by itself prove one universal consciousness}.
}
]

### Status

[
\mathbf R
]

with significant unresolved objections.

---

# 16. Recognition

Recognition is not adequately modelled as:

[
SM_i\rightarrow SM_i'.
]

That would reduce liberation to adoption of a new proposition.

A more faithful model is:

[
\boxed{
\mathcal R_i:
\Gamma_i\rightarrow\Gamma_i'
}
]

where the entire enacted relation among:

* self;
* world;
* agency;
* ownership;
* otherness;
* manifestation

is transformed.

Before recognition:

[
C_\infty
\text{ is apprehended as only }
\mathbb S_i.
]

After recognition:

[
C_\infty
\text{ is apprehended through }
\mathbb S_i.
]

The finite organization remains:

[
L_i\neq0.
]

What ceases is the claim:

[
\boxed{
\mathbb S_i
\text{ is an independent and exhaustive source of manifestation}.
}
]

Bäumer’s presentation of the *Pratyabhijñāhṛdayam* emphasizes recognition as an experiential key to nondual Śaivism rather than merely an intellectual reconstruction. ([Utpaladeva][9])

### Status

[
\mathbf R+\mathbf H
]

---

# 17. Four grades of recognition

## Model recognition

[
\mathcal R_1:
\text{The autobiographical ego is constructed}.
]

Compatible with naturalism.

## Relational recognition

[
\mathcal R_2:
\text{Self and world arise through reciprocal organism–environment dynamics}.
]

Compatible with enactivism.

## Phenomenological recognition

[
\mathcal R_3:
\text{Manifestation is not an object generated or owned by the ego}.
]

Philosophically stronger, but does not entail cosmic idealism.

## Full Pratyabhijñā recognition

[
\boxed{
\mathcal R_4:
C_i\equiv_i C_\infty.
}
]

The finite subject recognizes itself as a mode of one universal, self-manifest and free consciousness.

Only (\mathcal R_4) constitutes the tradition’s complete metaphysical claim.

---

# 18. What the framework proves about contraction

## Proposition 1 — Determinate experience requires differentiation

[
M_{\mathrm{determinate}}
\rightarrow
D.
]

Something appearing as (x) entails a contrast with what is not (x).

## Proposition 2 — A local perspective requires asymmetric access

[
P_i(x)\neq P_j(x).
]

A perspective is access from somewhere, through particular capacities and relations.

## Proposition 3 — Finite agency requires structured limitation

[
P_i
\rightarrow
L_i.
]

A biologically finite knower must possess restricted information, action, valuation, temporal processing and causal reach.

## Proposition 4 — Exclusive individuality requires more than limitation

[
B_i
===

L_i+X_i+I_i.
]

Bondage requires treating finite differentiation as ontologically exhaustive separation.

## Proposition 5 — Recognition cannot eliminate all finite architecture

Recognition itself requires:

* embodiment;
* differentiation;
* memory;
* temporal occurrence;
* a functioning subject–world relation.

Therefore:

[
\mathcal R_i
\not\Rightarrow
L_i=0.
]

Instead:

[
\boxed{
\mathcal R_i
\Rightarrow
L_i\text{ persists while }I_i\text{ is transformed}.
}
]

These propositions produce a strong reconstruction of embodied liberation.

### Status

[
\mathbf C+\mathbf H
]

---

# 19. The corrected scientific comparison

## Emergent naturalism

[
E
\rightarrow
\mathbb S_i
\rightarrow
\Gamma_i
\rightarrow
W_i
\rightarrow
M_i.
]

Nonphenomenal causal dynamics form bounded agents, cognition and organism-relative worlds; phenomenal manifestation eventually emerges.

Unresolved step:

[
W_i\rightarrow M_i.
]

## Organizational identity

[
M_i
\equiv
\operatorname{Organization}
(
\mathbb S_i,\Gamma_i,W_i
).
]

Phenomenality is identical with the system’s intrinsic organization rather than produced as an additional output.

Unresolved step:

> Why does that organization possess an intrinsic first-person character?

## Neutral or dual-aspect monism

[
U_i
\rightarrow
\begin{cases}
\mathbb S_i,\Gamma_i,W_i\
M_i
\end{cases}
]

Causal and phenomenal properties are two aspects of one underlying process.

Unresolved step:

> What determines their correspondence and unity?

## Pratyabhijñā

[
\boxed{
C_\infty
\xrightarrow{\delta_i}
\langle
\mathbb S_i,\Gamma_i,W_i
\rangle.
}
]

The body, subject, world, constraints and relations are all finite forms of self-manifest consciousness.

Manifestation is not a later output:

[
M_i\notin
\text{final stage of the pipeline}.
]

The entire finite structure is already a mode of manifest agency.

Unresolved step:

> Why must the common ground be one universal self-determining subject?

---

# 20. Where Pratyabhijñā is strongest

The framework strongly pressures theories that try to derive the following from wholly non-perspectival dynamics without remainder:

* intrinsic significance;
* first-person ownership;
* unified agency;
* determinate meaning;
* manifestation;
* the experienced unity of temporally distributed processes.

Its strongest insight is:

[
\boxed{
\text{meaningful differentiation is not equivalent to bare physical difference}.
}
]

A difference becomes meaningful only relative to a system for which it affects action, valuation or identity.

Pratyabhijñā radicalizes this:

[
\boxed{
\text{determination is an activity of self-manifest consciousness}.
}
]

Prueitt’s and Lawrence’s studies show how the Śaivas transform Buddhist exclusion theory: conceptual determination is not merely imposed upon independent particulars but becomes consciousness’s own power of carving a practical world from an underlying unity. ([PhilPapers][10])

### Status

[
\mathbf R
]

---

# 21. Where the argument remains unproven

Pratyabhijñā can argue:

[
\text{all known objects are manifest through consciousness}.
]

It can argue:

[
\text{objects as cognized cannot be separated from modes of manifestation and determination}.
]

It can challenge accounts of cognition as inert or purely mechanical.

But this does not deductively establish:

[
\boxed{
\text{all reality is one consciousness}.
}
]

The crucial invalid inference would be:

[
\text{Reality is accessible only through consciousness}
]

therefore:

[
\text{Reality exists only as consciousness}.
]

That confuses:

[
\text{epistemic dependence}
]

with:

[
\text{ontological constitution}.
]

Ratié identifies idealism as central to Pratyabhijñā and reconstructs its attempt to eliminate genuine otherness outside consciousness; this makes the intended conclusion clear but does not remove the realist’s objection. ([PhilPapers][11])

---

# 22. The strongest universalization argument

The best available Pratyabhijñā argument is abductive and transcendental rather than strictly deductive.

## P1

Consciousness manifests many changing contents while not being identical with any one content.

[
C(x)\rightarrow C(y)
]

while:

[
C\neq x,
\qquad
C\neq y.
]

## P2

Determinate objects are available only through acts of manifestation and exclusion.

[
O_i
\rightarrow
\operatorname{ManifestedAndDetermined}(O_i).
]

## P3

Subject–object separation is itself constituted within cognition through exclusion and limited self-apprehension.

## P4

No object categorically external to manifestation can be presented as such without becoming a manifested object.

## P5

A single form-assuming consciousness explains:

* unity through cognitive transformations;
* manifestation of objects;
* determination;
* memory;
* action;
* apparent otherness

without positing an unknowable external substance.

## Conclusion

[
\boxed{
C_\infty
\text{ is proposed as the most unified explanation of experience}.
}
]

This is explanatory unification.

It is not an incontrovertible deduction.

A realist can still answer:

[
\boxed{
\text{epistemic inaccessibility outside consciousness does not entail ontological nonexistence}.
}
]

---

# 23. Final standardized framework

## Universal reality

[
\boxed{
C_\infty
========

\langle
P,V,F
\rangle
}
]

Universal self-manifest, self-determining agency.

## Finite determination

[
\boxed{
\delta_i
========

\langle
K_i,A_i,V_i,T_i,C_i,X_i
\rangle
}
]

A restricted mode of knowledge, action, valuation, temporal access, causal situation and exclusion.

## Embodied manifestation

[
\boxed{
\delta_i(C_\infty)
==================

\langle
\mathbb S_i,W_i,\Gamma_i
\rangle
}
]

A nested ecology of embodied agencies, its determinate world, and the relation through which each constitutes the other.

## Finite limitation

[
\boxed{
L_i
===

\langle
K_i,A_i,V_i,T_i,C_i
\rangle.
}
]

The architecture required for a finite perspective.

## Bondage

[
\boxed{
B_i
===

L_i
+
\operatorname{AbsoluteIdentification}(\mathbb S_i)
+
\operatorname{Externalization}(W_i).
}
]

Finite architecture interpreted as independent and exhaustive selfhood.

## Recognition

[
\boxed{
\mathcal R_i:
\delta_i(C_\infty)
\text{ is recognized as a mode of }
C_\infty.
}
]

The local organization remains, but it is no longer apprehended as the independent owner and producer of manifestation.

---

# 24. What is now established

The following claims are defensible:

[
\boxed{
\text{For Pratyabhijñā, finite consciousness is not generated by}
}
]

[
\boxed{
\text{sufficiently complex nonconscious organization.}
}
]

[
\boxed{
\text{Finite subjects and worlds are mutually constituted modes of}
}
]

[
\boxed{
\text{universal self-manifest agency.}
}
]

[
\boxed{
\text{The kañcukas can be reconstructed as interdependent}
}
]

[
\boxed{
\text{coordinates of finite knowledge, action, value, time and causation.}
}
]

[
\boxed{
\text{Exclusion converts limitation into exclusive subject–object separation.}
}
]

[
\boxed{
\text{Embodied liberation cannot require the elimination of all finite constraints.}
}
]

[
\boxed{
\text{Recognition transforms identification and the enacted subject–world relation.}
}
]

---

# 25. What remains unresolved

Exactly one foundational inference remains:

[
\boxed{
\textbf{Why must the ground of all finite manifestation be one}
}
]

[
\boxed{
\textbf{self-determining subject rather than a neutral reality}
}
]

[
\boxed{
\textbf{that produces multiple local subjects?}
}
]

The scholars establish that Pratyabhijñā asserts this universal identity and develops sophisticated arguments for it.

They do not turn it into an uncontested theorem.

The exact frontier is:

[
\boxed{
\text{common structural dependence}
\not\Rightarrow
\text{numerical identity}.
}
]

Every local subject may depend upon the same kind of manifest structure without being a mode of numerically one consciousness.

Pratyabhijñā must therefore establish not merely:

[
\forall i,;C_i\text{ is self-manifest},
]

but:

[
\boxed{
\forall i,j,;C_i=C_j=C_\infty.
}
]

That universalization step is the next proof.

The framework now has a clean epistemic boundary: the kañcuka–finite-agency reconstruction is strong; subject–world co-determination is highly defensible; recognition as transformation rather than mere belief is textually coherent; **numerical identity between every local field and one universal consciousness remains the unresolved Pratyabhijñā wager**.

[1]: https://academic.oup.com/edited-volume/27982/chapter-abstract/211671490?utm_source=chatgpt.com "Utpaladeva and Abhinavagupta on the Freedom of Consciousness | The Oxford Handbook of Indian Philosophy | Oxford Academic"
[2]: https://www.wisdomlib.org/hinduism/book/tantraloka-sanskrit-text/d/doc488215.html?utm_source=chatgpt.com "Tantraloka Verse 9.183 [Sanskrit text]"
[3]: https://www.wisdomlib.org/hinduism/book/tantraloka-sanskrit-text/d/doc488236.html?utm_source=chatgpt.com "Tantraloka Verse 9.204 [Sanskrit text]"
[4]: https://www.mdpi.com/2077-1444/9/6/191?utm_source=chatgpt.com "Pratyabhijñā Apoha Theory, Shannon–Weaver Information, Saussurean Structure, and Peircean Interpretant Agency"
[5]: https://academic.oup.com/book/45384?utm_source=chatgpt.com "The Matter of Wonder: Abhinavagupta's Panentheism and the New Materialism | Oxford Academic"
[6]: https://academic.oup.com/book/45384/chapter/389330161?utm_source=chatgpt.com "The Matter of Wonder | The Matter of Wonder: Abhinavagupta's Panentheism and the New Materialism | Oxford Academic"
[7]: https://iris.uniroma1.it/handle/11573/155566?utm_source=chatgpt.com "The Isvarapratyabhijnakarika of Utpaladeva with the author's vrtti. Critical edition and annotated translation."
[8]: https://www.cambridge.org/core/journals/journal-of-the-american-philosophical-association/article/recall-the-memory-argument-for-inner-awareness/8DC8F42819A018D9D9DFACE11E4B972D?utm_source=chatgpt.com "Recall the Memory Argument for Inner Awareness | Journal of the American Philosophical Association | Cambridge Core"
[9]: https://www.utpaladeva.in/events-seminars-lectures/past?utm_source=chatgpt.com "Past: Bettina Sharada Bäumer"
[10]: https://philpapers.org/rec/PRUBTN?utm_source=chatgpt.com "Catherine Prueitt, Beyond Time, Not Before Time: The Pratyabhijñā S'aiva Critique of Dharmakīrti on the Reality of Beginningless Conceptual Differentiation - PhilPapers"
[11]: https://philpapers.org/rec/RATOIT?utm_source=chatgpt.com "Isabelle Ratié, Otherness in the pratyabhijñā philosophy - PhilPapers"
