The cleanest synthesis is not to “map Śaiva terms onto neuroscience.” It is to build a **shared process language** in which Trika and science make claims at different explanatory levels.

Your attached reconstruction already supplies the core insight: the tattvas can be read as a transition from unrestricted manifestation through subject–object articulation and structured limitation into a finite cognitive agent and an actionable material world. But this is a philosophical reconstruction, not a claim that Abhinavagupta secretly formulated modern computational neuroscience. 

# A standardized framework

Use six levels and never collapse them:

[
\boxed{
\mathcal{M}\rightarrow\mathcal{D}\rightarrow\mathcal{B}
\rightarrow\mathcal{N}\rightarrow\mathcal{W}\rightarrow\mathcal{R}
}
]

where:

[
\mathcal{M}=\text{manifestation}
]

[
\mathcal{D}=\text{differentiation}
]

[
\mathcal{B}=\text{bounded embodiment}
]

[
\mathcal{N}=\text{normative agency}
]

[
\mathcal{W}=\text{world-model or enacted world}
]

[
\mathcal{R}=\text{recognition}
]

Science currently explains much of:

[
\mathcal{D}\rightarrow\mathcal{B}\rightarrow
\mathcal{N}\rightarrow\mathcal{W}
]

Pratyabhijñā proposes:

[
\mathcal{M}\rightarrow\mathcal{D}
]

and interprets recognition as:

[
\mathcal{R}:
\mathcal{W}\rightarrow
\text{awareness of its dependence upon }\mathcal{M}
]

The entire dispute concerns whether (\mathcal{M}) is:

1. generated by the later levels;
2. identical with their organization;
3. ontologically prior to them.

---

# 1. Manifestation

## Neutral definition

[
\mathcal{M}=
\text{the occurrence of phenomenal presence}
]

This means only:

> Something appears.

It does not yet mean:

* one universal consciousness;
* an eternal self;
* agency;
* intelligence;
* metaphysical idealism.

## Trika vocabulary

[
\mathcal{M}\approx prakāśa
]

But this equivalence is provisional because Pratyabhijñā immediately adds that genuine manifestation is inseparable from *vimarśa*.

## Scientific status

No scientific theory has established a generally accepted derivation:

[
\text{nonphenomenal organization}
\Rightarrow
\mathcal{M}
]

IIT 4.0 formally identifies experience with irreducible intrinsic cause–effect structure, but this is built by translating phenomenological axioms into physical postulates; it is not a theorem accepted independently of IIT’s assumptions. ([PLOS][1])

The recent large adversarial collaboration comparing IIT and Global Neuronal Workspace Theory challenged important predictions of both theories rather than selecting a decisive winner. It identified neural findings relevant to conscious content, but it did not settle why those processes are phenomenally manifest. ([Nature][2])

### Standardized rule

Never write:

[
\text{consciousness}=\text{integration}
]

Write:

[
\text{IIT hypothesis:}\quad
\mathcal{M}\equiv
\text{intrinsic integrated cause–effect structure}
]

That preserves the difference between data and interpretation.

---

# 2. Differentiation

## Neutral definition

[
\mathcal{D}=
\text{the formation of distinguishable states and relations}
]

For a determinate state (x):

[
x\neq_c y
]

where (c) is the criterion under which they differ.

No determinate experience can contain literally no differentiation:

[
\mathcal{M}_{determinate}\rightarrow\mathcal{D}
]

## Trika vocabulary

The pure tattvas describe increasingly explicit configurations of:

[
aham=\text{subject pole}
]

and:

[
idam=\text{object pole}
]

The sequence is not yet separation:

[
\text{Śiva}
\rightarrow
\text{Śakti}
\rightarrow
\text{Sadāśiva}
\rightarrow
\text{Īśvara}
\rightarrow
\text{Śuddhavidyā}
]

It can be standardized as:

[
\text{manifestness}
\rightarrow
\text{self-related capacity}
\rightarrow
\text{incipient object-directedness}
\rightarrow
\text{determinate object presentation}
\rightarrow
\text{balanced subject–object articulation}
]

This supports the important distinction:

[
\boxed{
\text{differentiation}\neq\text{separation}
}
]

## Scientific correlate

Science models differentiation through:

* state-space partitioning;
* feature discrimination;
* symmetry breaking;
* causal differentiation;
* predictive state estimation.

But these models do not prove that differentiation is an activity of consciousness.

### Standardized rule

Use:

[
\mathcal{D}=
\text{state differentiation}
]

and reserve:

[
vimarśa=
\text{the Trika claim that differentiation is intrinsically self-apprehending}
]

Do not translate *vimarśa* simply as “information processing.”

---

# 3. Boundary and contraction

## Neutral definition

A system (S) is operationally bounded when its internal and external states interact through restricted channels:

[
E\rightarrow B_s\rightarrow I
]

[
I\rightarrow B_a\rightarrow E
]

where:

* (B_s) are sensory boundary states;
* (B_a) are active boundary states;
* (I) are internal states;
* (E) are external states.

A Markov blanket defines a conditional-independence structure:

[
I\perp E\mid B
]

This gives a statistical boundary, not automatically a living organism, mind, self, or phenomenal subject.

Nested Markov blankets can model how smaller bounded systems form larger bounded systems. ([PubMed][3])

But critics correctly emphasize that a Markov blanket alone does not determine the boundary of a mind. Statistical conditional independence is too permissive and depends partly on the chosen variables and model. ([PubMed][4])

## Trika vocabulary

The standardized translation of *saṃkoca* should be:

[
\boxed{
\textit{saṃkoca}
================

\text{restriction of operative access, capacity and identification}
}
]

It is not equivalent to a Markov blanket.

Instead:

[
\text{Markov blanket}
=====================

\text{one possible mathematical model of operational restriction}
]

while:

[
\textit{saṃkoca}
================

\text{the broader metaphysical and phenomenological claim that unrestricted power appears through finite constraints}
]

## Māyā

Use:

[
\boxed{
Māyā=
\text{conversion of internal differentiation into exclusive standpoint dependence}
}
]

Operationally:

[
Access_i(x)\neq Access_j(x)
]

A finite perspective has access from one location, through one history, one body and one set of channels.

This is stronger and cleaner than calling Māyā “illusion.”

---

# 4. The five kañcukas as an agent coordinate system

This is the strongest common language.

Define a finite agent (A_i) by:

[
A_i=
\langle
\mathcal{K}_i,
\mathcal{A}_i,
\mathcal{V}_i,
\mathcal{T}_i,
\mathcal{C}_i
\rangle
]

where:

[
\mathcal{K}_i=\text{accessible information}
]

[
\mathcal{A}_i=\text{available action policies}
]

[
\mathcal{V}_i=\text{preferred and viable states}
]

[
\mathcal{T}_i=\text{temporal horizon}
]

[
\mathcal{C}_i=\text{causal and spatial situation}
]

Now map the kañcukas structurally:

| Kañcuka  | Standard variable | Scientific language                                         |
| -------- | ----------------- | ----------------------------------------------------------- |
| *vidyā*  | (\mathcal K_i)    | partial observability, sensory bandwidth, model uncertainty |
| *kalā*   | (\mathcal A_i)    | action repertoire, policy space, effectors                  |
| *rāga*   | (\mathcal V_i)    | preferences, valence, viability conditions                  |
| *kāla*   | (\mathcal T_i)    | temporal depth, memory and planning horizon                 |
| *niyati* | (\mathcal C_i)    | causal location, embodiment, transition constraints         |

This is not word-for-word translation. It is a **shared formal role**.

## The agent theorem

A determinate agent requires restrictions on all five coordinates:

[
A_i\Rightarrow
\mathcal{K}_i,\mathcal{A}_i,\mathcal{V}_i,
\mathcal{T}_i,\mathcal{C}_i
\text{ are finite}
]

Why?

### Unrestricted information

If everything were equally available:

[
\mathcal K_i=\mathcal K_\infty
]

there would be no local uncertainty or informational perspective.

### Unrestricted action

If every outcome were immediately realizable:

[
\mathcal A_i=\mathcal A_\infty
]

there would be no policy selection.

### No preference

If all states had equal value:

[
\forall s,\quad V(s)=constant
]

there would be no goal-directed correction.

### No temporal restriction

If all events were simultaneously available:

[
\mathcal T_i=\mathcal T_\infty
]

there would be no anticipation, memory, learning or risk.

### No causal location

If the agent could produce every result from every state:

[
P(s'|s,a)=1
]

for all outcomes, there would be no particular environment or embodied trajectory.

Therefore:

[
\boxed{
\text{structured limitation is constitutive of determinate agency}
}
]

This is the rigorous scientific version of your contraction insight.

---

# 5. Normativity and rāga

Active inference gives a formal language for goal-directed persistence.

Let:

[
o_{1:T}=\text{observations}
]

[
s_{1:T}=\text{hidden states}
]

[
\pi=\text{policy}
]

[
q(s)=\text{system’s approximate posterior}
]

The system updates its internal states to reduce variational free energy:

[
F[q]=
D_{KL}\big(q(s)\parallel p(s|o)\big)-\ln p(o)
]

and selects policies according to expected free energy:

[
G(\pi)
]

which incorporates expected outcomes, uncertainty and information gain.

In biological interpretations, preferred outcomes encode characteristic or viable states.

This corresponds structurally to:

[
\textit{rāga}
\approx
\text{asymmetric valuation of possible states}
]

But the equivalence must remain qualified.

Active inference says:

[
\text{the model contains prior preferences}
]

Trika says:

[
\text{finite desire arises because plenitude appears as lack}
]

Science explains how preferences regulate action. It does not establish the metaphysical narrative that unlimited fulfilment has contracted into lack.

Enactivism similarly grounds minimal normativity in precarious self-maintenance: environmental events become beneficial or harmful relative to the continued organization of the living system. ([PubMed][5])

### Standardized distinction

[
\mathcal V_i=
\text{operational normativity}
]

[
rāga=
\text{Trika interpretation of finite normativity as contracted plenitude}
]

This stops the comparison becoming vague.

---

# 6. Multiscale agency and contraction

Levin’s “cognitive light cone” can be standardized as:

[
\Lambda_i=
\left{
x,t:
A_i\text{ can sense, model, value or affect }x
\text{ across timescale }t
\right}
]

Larger cognitive light cones contain goals extending further through space, time and problem spaces.

Cells possess relatively local horizons.

Tissues can regulate larger anatomical states.

Organisms can regulate behavioural and social states.

Levin’s framework therefore supports:

[
\boxed{
\text{selfhood is graded by the scope of integrated concern and control}
}
]

rather than by a binary soul/no-soul distinction. ([PubMed Central (PMC)][6])

This gives a precise correlate of **degree of contraction**:

[
DegreeOfContraction_i
\propto
\frac{1}{|\Lambda_i|}
]

This is only schematic. A larger light cone does not necessarily imply greater consciousness or liberation.

A cancer cell may have a narrower organismic horizon than a normally coordinated cell, but a large human bureaucracy may have a vast control horizon without being one phenomenal subject.

Therefore distinguish:

[
\Lambda_i=
\text{agential scope}
]

from:

[
\Phi_i=
\text{hypothesized phenomenal integration}
]

and:

[
M_i=
\text{actual phenomenal manifestation}
]

They are not interchangeable.

---

# 7. Causal emergence and real higher-level selves

Wallace’s pattern realism and causal-emergence research solve a major part of the ontology.

A higher-level agent need not be fundamental to be real.

Let microstates be:

[
x\in X
]

and a macrostate be a coarse-graining:

[
y=g(x)
]

A macro-description is causally significant when interventions and transitions at (Y) are less noisy or more informative than descriptions at the microlevel.

Causal-emergence work demonstrates formally that coarse-grained macroscales can, under some measures and systems, possess stronger or uniquely informative causal structure despite being physically realized by microstates. ([arXiv][7])

Therefore:

[
\boxed{
\text{a multicellular organism can be one real causal agent}
}
]

without requiring:

[
\text{one indivisible material substance}
]

This standardizes the Wallace–Levin side:

[
\text{self}
===========

\text{a causally efficacious, dynamically persistent macro-pattern}
]

Call it:

[
\mathcal S_i
]

This solves:

* system identity;
* multiscale agency;
* top-down constraint;
* persistence through component replacement.

It does not solve:

[
\mathcal S_i\Rightarrow M_i
]

A real causal whole need not automatically be one phenomenal whole.

---

# 8. The organism-relative world

Seth’s model can be expressed as:

[
W_i=
f(E,B_i,G_i,\Pi_i,H_i)
]

where:

* (E): shared causal environment;
* (B_i): body and sensory architecture;
* (G_i): generative model;
* (\Pi_i): available policies;
* (H_i): developmental and evolutionary history.

Objects are not passively copied.

They are stable hypotheses whose perceptual presence partly depends upon predicted sensorimotor consequences:

[
Object_i=
\text{inference about hidden causes}
+
\text{counterfactual action structure}
]

Seth’s work explicitly links perceptual presence to counterfactual sensorimotor predictions. ([PubMed][8])

Thus:

[
W_{\text{bat}}\neq W_{\text{dog}}\neq W_{\text{human}}
]

These are different enacted worlds or *Umwelten*, not necessarily different external physical universes.

## Standard vocabulary

Use:

[
E=\text{causal environment}
]

[
W_i=\text{world-for-agent }i
]

[
X_i=\text{phenomenally experienced world}
]

Then:

[
E\rightarrow W_i
]

is scientifically tractable.

But:

[
W_i\rightarrow X_i
]

remains theoretically contested.

This prevents the word “world” from sliding between physics, cognition and phenomenology.

---

# 9. Ahaṃkāra and the self-model

Define:

[
SM_i=
\text{the system’s model of itself as a body, agent and autobiographical centre}
]

It includes estimates of:

* bodily location;
* ownership;
* action authorship;
* memory continuity;
* social identity;
* possible futures.

This is the clean correlate of:

[
ahaṃkāra=
\text{appropriative finite self-model}
]

But not of primordial:

[
aham=
\text{non-objective first-personality}
]

These must never be merged.

## Three levels of “I”

[
I_1=\text{minimal first-person organization}
]

[
I_2=\text{embodied self-model}
]

[
I_3=\text{narrative and social ego}
]

Trika adds:

[
I_\infty=
\text{unrestricted }aham
]

Science gives increasingly strong models of (I_1), (I_2), and (I_3).

The philosophical question is whether:

[
I_1
]

is produced by bounded organization or is a local expression of:

[
I_\infty
]

---

# 10. Recognition as model revision

Recognition can now be given a scientifically neutral definition.

Let the contracted self-model contain:

[
SM_i:
\quad
\text{“I am exclusively this bounded organism.”}
]

Recognition is a higher-order revision:

[
\mathcal R_i:
SM_i\rightarrow SM_i'
]

where:

[
SM_i'=
\text{“This organism is my operative perspective,}
]

[
\text{but the represented ego is not the complete condition of manifestation.”}
]

This revision can alter:

* ownership;
* attentional precision;
* defensive reactivity;
* boundaries of identification;
* temporal concern;
* perceived relation between self and world.

The active-inference vocabulary would describe this partly as:

* revision of high-level priors;
* altered precision weighting;
* reduced certainty assigned to the autobiographical self-model;
* expanded hierarchical context;
* changes in policy selection.

Recent active-inference theories of consciousness and altered states explicitly attempt to model consciousness through global precision forecasting and hierarchical inference, but these remain developing frameworks rather than established explanations of Pratyabhijñā recognition. ([arXiv][9])

## Strong versus weak recognition

### Weak recognition

[
\mathcal R_w:
\text{the ego is a model, not an independent controller}
]

This is compatible with naturalism.

### Relational recognition

[
\mathcal R_r:
\text{self and world are mutually constituted within organism–environment dynamics}
]

This is compatible with enactivism.

### Phenomenological recognition

[
\mathcal R_p:
\text{manifestation is not itself an object owned by the ego}
]

This is stronger but remains phenomenologically defensible.

### Full Śaiva recognition

[
\mathcal R_s:
M_i=M_\infty=\text{Śiva}
]

This claims that local manifestation is numerically identical with universal consciousness.

Science does not presently establish (\mathcal R_s).

---

# 11. The complete shared process model

The unified framework is:

[
\boxed{
\Omega=
\langle
E,\mathcal S_i,B_i,\Lambda_i,
\mathcal K_i,\mathcal A_i,\mathcal V_i,
\mathcal T_i,\mathcal C_i,G_i,W_i,SM_i,M_i
\rangle
}
]

## Environment

[
E=
\text{causal dynamics not exhausted by the agent’s model}
]

## Emergent system

[
\mathcal S_i=
\text{dynamically persistent causal pattern}
]

## Boundary

[
B_i=
\text{selective interface between internal and external dynamics}
]

## Cognitive light cone

[
\Lambda_i=
\text{scope of accessible and controllable states}
]

## Limitation coordinates

[
L_i=
\langle
\mathcal K_i,\mathcal A_i,\mathcal V_i,
\mathcal T_i,\mathcal C_i
\rangle
]

## Generative model

[
G_i=
\text{structured expectations about hidden causes and actions}
]

## Enacted world

[
W_i=
f(E,\mathcal S_i,B_i,L_i,G_i)
]

## Self-model

[
SM_i=
\text{model locating the system as an agent within }W_i
]

## Phenomenal field

[
M_i=
\text{whether and how }W_i\text{ is manifest}
]

## Recognition

[
\mathcal R_i=
\text{revision of }SM_i
\text{ and its relation to }M_i
]

---

# 12. Mapping the tattva architecture

The mapping should be functional, not literal.

| Trika layer   | Shared process role                         | Scientific framework                                   |
| ------------- | ------------------------------------------- | ------------------------------------------------------ |
| Śiva          | manifestation without specified restriction | no established scientific equivalent                   |
| Śakti         | capacity for self-articulation              | intrinsic causal power or dynamic potential, disputed  |
| Sadāśiva      | subject-dominant directedness               | proto-intentional organization; analogy only           |
| Īśvara        | determinate object presentation             | generative perceptual content                          |
| Śuddhavidyā   | coordinated subject–object structure        | agent–world relational model                           |
| Māyā          | exclusive standpoint differentiation        | partial observability and asymmetric access            |
| five kañcukas | finite-agent coordinate system              | bounded information, action, value, time and causation |
| Puruṣa        | one finite standpoint                       | operationally individuated agent                       |
| Prakṛti       | finite field of possible states             | organism-relative state and action space               |
| Buddhi        | determination                               | model selection, categorization, decision              |
| Ahaṃkāra      | appropriation                               | embodied and autobiographical self-model               |
| Manas         | coordination                                | attention and sensorimotor integration                 |
| Jñānendriyas  | discriminatory capacities                   | sensory channels                                       |
| Karmendriyas  | action capacities                           | effectors and policies                                 |
| Tanmātras     | accessible feature dimensions               | modality-specific latent features                      |
| Mahābhūtas    | stable material constraints                 | physical regularities and embodied resistance          |

The first five rows are philosophically suggestive but scientifically weak.

The strongest scientifically useful correspondence begins with:

[
Māyā\rightarrow kañcukas\rightarrow Puruṣa
]

because those describe the formation of one limited standpoint.

---

# 13. What the framework actually explains

It explains why a particular world requires contraction.

[
\boxed{
\text{No restriction}
\Rightarrow
\text{no particular access}
\Rightarrow
\text{no particular perspective}
}
]

It explains why different animals inhabit different worlds:

[
W_i=f(E,B_i,L_i,G_i)
]

It explains why a body is not merely a prison:

[
B_i+L_i
]

are the conditions for:

* perception;
* action;
* value;
* memory;
* learning;
* stakes;
* discovery.

It explains how smaller agents become larger agents:

[
\mathcal S_1+\cdots+\mathcal S_n
\rightarrow
\mathcal S_{macro}
]

when coupling produces a higher-scale causal and normative organization.

It explains why liberation cannot mean deleting all contraction:

[
L_i=0
\Rightarrow
\text{no finite cognition, memory or recognition event}
]

Therefore embodied recognition must be:

[
L_i\text{ remains}
]

while:

[
SM_i\neq\text{ultimate identity}
]

---

# 14. What it does not explain

## Manifestation

Nothing in Markov blankets, active inference, causal emergence or predictive processing proves:

[
\mathcal S_i\rightarrow M_i
]

The 2024–2025 active-inference consciousness programme proposes testable commitments concerning temporally deep generative models, counterfactual inference and precision, but it remains a theory of which computational features accompany or constitute consciousness—not an independently proven derivation of phenomenality. ([arXiv][9])

## One universal field

Even if every organism has:

[
M_i
]

it does not follow:

[
M_1=M_2=\cdots=M_\infty
]

Common structure is not numerical identity.

## Divine agency

Even if fundamental reality is intrinsically manifest:

[
M_\infty
]

it does not follow that it possesses:

[
\text{will, intention or absolute freedom}
]

Self-organization is not automatically deliberate play.

## Why these particular laws

The framework explains how constraints generate particular agents once physical and biological regularities are given.

It does not explain why the universe has exactly these regularities, organisms, evolutionary histories and distributions of suffering.

---

# 15. The real frontier after standardization

The old question:

> Why is consciousness bounded here?

splits into four precise problems.

## Boundary problem — largely tractable

[
\text{Why does this system have selective causal access?}
]

Answered through embodiment, conditional independence, sensory and active channels, developmental closure and multiscale regulation.

## Agent problem — increasingly tractable

[
\text{Why does this bounded system act as one goal-directed whole?}
]

Answered through organizational closure, active inference, collective intelligence, causal emergence and top-down constraints.

## World problem — increasingly tractable

[
\text{Why does this body enact this particular world?}
]

Answered through morphology, sensory channels, generative models, history, counterfactual action and organism-specific preferences.

## Manifestation problem — unresolved

[
\text{Why is the enacted world phenomenally present?}
]

This is where science and Pratyabhijñā still divide.

---

# 16. The exact Pratyabhijñā hypothesis

The framework lets us state it without mystification:

[
\boxed{
\textbf{Finite consciousness is not produced when an agent model becomes sufficiently complex.}
}
]

Rather:

[
\boxed{
\textbf{An agent is the restriction of intrinsically manifest, self-articulating reality through a finite constraint-set }L_i.
}
]

Formally:

[
M_\infty
\xrightarrow{L_i}
M_i
]

and:

[
M_i+
B_i+G_i+SM_i
\rightarrow
W_i
]

Here:

* (M_\infty) is universal manifest capacity;
* (L_i) restricts access, action, value, time and causal position;
* (M_i) is a local phenomenal field;
* (W_i) is its organism-relative world.

This is the standardized form of contraction.

But the scientific rival is:

[
E
\xrightarrow{\text{self-organization}}
\mathcal S_i
\xrightarrow{B_i,L_i,G_i}
W_i
\xrightarrow{?}
M_i
]

The two models differ only in the direction of the last ontological dependency:

[
\textbf{Naturalistic emergence:}
\quad
\mathcal S_i\rightarrow M_i
]

[
\textbf{Dual-aspect identity:}
\quad
\mathcal S_i\equiv M_i
]

[
\textbf{Pratyabhijñā contraction:}
\quad
M_\infty\rightarrow\mathcal S_i
]

That is the clean comparison.

---

# Final framework

The standardized language should use four ontological commitments:

### Level 0 — Dynamics

[
E
]

Physical and causal relations.

### Level 1 — Agency

[
\mathcal S_i,B_i,L_i,\Lambda_i
]

An emergent bounded process with concerns and control.

### Level 2 — Cognition

[
G_i,W_i,SM_i
]

A generative model, enacted world and localized self-model.

### Level 3 — Manifestation

[
M_i
]

The phenomenal presence of that world.

### Level 4 — Universalization

[
M_\infty
]

The hypothesis that all local manifestation is restriction of one universal self-manifest reality.

Science has substantial explanatory machinery for Levels 0–2.

Consciousness science attempts to connect Levels 2 and 3 but has no consensus.

Pratyabhijñā begins at Level 3 and claims Level 4.

Its strongest scientifically compatible thesis is:

[
\boxed{
\textbf{A body is a constraint architecture that converts open possibility into one temporally extended world of limited knowledge, action and value.}
}
]

Its unproved metaphysical thesis is:

[
\boxed{
\textbf{The manifestness within every such world is numerically one unrestricted consciousness contracting through different architectures.}
}
]

That is now the single frontier. Everything else—boundary formation, organism-specific worlds, multiscale agency, predictive perception and real emergent selves—can be discussed in one coherent scientific language without pretending that those results prove Śiva.

[1]: https://journals.plos.org/ploscompbiol/article?id=10.1371%2Fjournal.pcbi.1011465&utm_source=chatgpt.com "Integrated information theory (IIT) 4.0 - Research journals"
[2]: https://www.nature.com/articles/s41586-025-08888-1?utm_source=chatgpt.com "Adversarial testing of global neuronal workspace and ..."
[3]: https://pubmed.ncbi.nlm.nih.gov/29343629/?utm_source=chatgpt.com "The Markov blankets of life: autonomy, active inference and ..."
[4]: https://pubmed.ncbi.nlm.nih.gov/36172779/?utm_source=chatgpt.com "Markov blankets do not demarcate the boundaries of ..."
[5]: https://pubmed.ncbi.nlm.nih.gov/34859293/?utm_source=chatgpt.com "The enactive naturalization of normativity: from self-maintenance to situated interactions - PubMed"
[6]: https://pmc.ncbi.nlm.nih.gov/articles/PMC8988303/?utm_source=chatgpt.com "Technological Approach to Mind Everywhere - PMC - NIH"
[7]: https://arxiv.org/abs/2202.01854?utm_source=chatgpt.com "Causal emergence is widespread across measures of causation"
[8]: https://pubmed.ncbi.nlm.nih.gov/24446823/?utm_source=chatgpt.com "A predictive processing theory of sensorimotor contingencies"
[9]: https://arxiv.org/abs/2410.06633?utm_source=chatgpt.com "On the Minimal Theory of Consciousness Implicit in Active Inference"
